version: "2"
services:
  app:
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: "npm start"
    depends_on:
      - mongo-seed
  
  mongo:
    image: mongo:4.0
    
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    