version: "2"
services:
  backend:
    build: ./backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    command: "yarn start.dev"
    environment:
      SPOTIFY_CLIENT_ID: 
      SPOTIFY_CLIENT_SECRET: 
      S3_BUCKET:

  
  mongo:
    image: mongo:4.0

  frontend:
    build: ./frontend
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    command: "yarn start"
    depends_on:
      - mongo-seed
    