version: "2"
services:
  app:
    build: .
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm start"
  
  mongo:
    image: mongo:4.0
    depends_on:
      - mongo-seed
    
  mongo-seed:
    build: ./mongo-seed
    