version: "2"
services:
  backend:
    build: ./backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    command: "yarn start"
    depends_on:
      - mongo-seed
  
  mongo:
    image: mongo:4.0
    
  mongo-seed:
    build: ./backend/mongo-seed
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    command: "yarn start"
    depends_on:
      - mongo-seed
    